# Generated by Django 6.0.7 on 2026-09-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('professional_summary', models.TextField(blank=True)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('experience_describtion', models.TextField(blank=True)),
                ('college', models.CharField(blank=True, max_length=150)),
                ('degree', models.CharField(blank=True, max_length=100)),
                ('passing_year', models.CharField(blank=True, max_length=20)),
                ('skill1', models.CharField(blank=True, max_length=100)),
                ('skill2', models.CharField(blank=True, max_length=100)),
                ('skill3', models.CharField(blank=True, max_length=100)),
                ('skill4', models.CharField(blank=True, max_length=100)),
                ('project_name', models.CharField(blank=True, max_length=150)),
                ('project_description', models.TextField(blank=True)),
                ('template', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
